name: Post Deploy Action

on:
  workflow_run:
    workflows: ["deploy-to-main"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification
        run: echo "Deploy to main branch completed successfully."
        # Add your steps here. This example simply prints a message.
